version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser       # את יכולה לשנות את זה
      POSTGRES_PASSWORD: mypassword # ואת זה
      POSTGRES_DB: learning_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: